// <auto-generated />
using Investips.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Investips.Persistence.Migrations
{
    [DbContext(typeof(InvestipsDbContext))]
    [Migration("20171003055338_AddUserRoleAndRelationship")]
    partial class AddUserRoleAndRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Investips.Core.Models.Chart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<string>("Resolution");

                    b.Property<string>("Symbol");

                    b.HasKey("Id");

                    b.ToTable("Charts");
                });

            modelBuilder.Entity("Investips.Core.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments")
                        .HasMaxLength(500);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Investips.Core.Models.PortfolioSecurity", b =>
                {
                    b.Property<int>("PortfolioId");

                    b.Property<int>("SecurityId");

                    b.HasKey("PortfolioId", "SecurityId");

                    b.HasIndex("SecurityId");

                    b.ToTable("PortfolioSecurity");
                });

            modelBuilder.Entity("Investips.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Investips.Core.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("Investips.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Investips.Core.Models.WidgetShape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SecurityId");

                    b.Property<string>("ShapeType");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.ToTable("WidgetShapes");
                });

            modelBuilder.Entity("Investips.Core.Models.WidgetShapePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Price");

                    b.Property<long>("Time");

                    b.Property<int?>("WidgetShapeId");

                    b.HasKey("Id");

                    b.HasIndex("WidgetShapeId");

                    b.ToTable("WidgetShapePoint");
                });

            modelBuilder.Entity("Investips.Core.Models.PortfolioSecurity", b =>
                {
                    b.HasOne("Investips.Core.Models.Portfolio", "Portfolio")
                        .WithMany("Securities")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Investips.Core.Models.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Investips.Core.Models.WidgetShape", b =>
                {
                    b.HasOne("Investips.Core.Models.Security", "Security")
                        .WithMany("WidgetShapes")
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Investips.Core.Models.WidgetShapePoint", b =>
                {
                    b.HasOne("Investips.Core.Models.WidgetShape")
                        .WithMany("WidgetShapePoints")
                        .HasForeignKey("WidgetShapeId");
                });
#pragma warning restore 612, 618
        }
    }
}
